import { WorkflowStage } from "../types";
import { stageRegistry } from "../config/stageRegistry";

/**
 * Maps generic ContentPrimitive fields (title, content) to collection-specific fields (name, description).
 * This ensures compatibility with legacy "Character Bible" and "Location Bible" schemas.
 */
export function mapPrimitiveToDb(stage: WorkflowStage | string, data: Record<string, unknown>): Record<string, unknown> {
  const safeData = { ...data };
  
  const isBible = stageRegistry.getCategory(stage) === 'BIBLE';
  
  if (isBible) {
    if (data.title !== undefined) safeData.name = data.title;
    if (data.content !== undefined) safeData.description = data.content;
  }
  
  return safeData;
}
/**
 * Recursively removes undefined values from an object or array.
 * Required for Firestore writes as it throws on undefined fields.
 */
export function stripUndefined<T>(obj: T): T {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(stripUndefined).filter(v => v !== undefined) as unknown as T;
  return Object.fromEntries(
    Object.entries(obj)
      .filter(([_, v]) => v !== undefined)
      .map(([k, v]) => [k, stripUndefined(v)])
  ) as unknown as T;
}

/**
 * Checks if a string ID is a temporary ID generated by agents.
 * Temporary IDs usually have a prefix followed by an underscore or a random string.
 */
export function isTemporaryId(id: string): boolean {
  if (!id) return true;
  // Firestore IDs are usually 20 chars long, alphanumeric.
  // Agents use prefixes like beat_, treatment_, char_gen_, etc.
  return id.includes('_') || id.length < 15;
}
